!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 4
    t: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 33, y: 0, z: 7}
      rotations: [135]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 8, y: 0, z: 32}
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
